version: '3.8'

services:
  suggestions-microservice:
    build: apps/suggestions/.
    env_file:
      - apps/suggestions/.env.docker
    ports:
      - "8002:8002"

  articles-microservice:
    build: apps/articles/.
    env_file:
      - apps/articles/.env.docker
    ports:
      - "8001:8001"
    depends_on:
      - suggestions-microservice

networks:
  default:
    name: microservices
    driver: bridge
