version: '3.8'

services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "16685:16685" # grpc server for jaeger-query service
      - "16686:16686" # http server for Jaeger-query UI
      - "4317:4317" # grpc

networks:
  default:
    name: microservices
    external: true


